
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>GemSwords</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <AdditionalFiles Remove="Localization\**" />
    <Compile Remove="bak\**" />
    <Compile Remove="Localization\**" />
    <EmbeddedResource Remove="bak\**" />
    <EmbeddedResource Remove="Localization\**" />
    <None Remove="bak\**" />
    <None Remove="Localization\**" />
  </ItemGroup>
</Project>